package com.mycompany.GUI;


import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class interfazInventario extends javax.swing.JFrame {
    
    public interfazInventario() {
        initComponents();
        cargarInventario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datosInventario = new javax.swing.JDialog();
        titJdiag = new javax.swing.JLabel();
        titnomInvdiag = new javax.swing.JLabel();
        txtfieldNomInv = new javax.swing.JTextField();
        titCantInvdiag = new javax.swing.JLabel();
        txtfieldcantInvdiag = new javax.swing.JTextField();
        titprecInvdiag = new javax.swing.JLabel();
        txtfieldprecInvdiag = new javax.swing.JTextField();
        diagagreInv = new javax.swing.JButton();
        datosInventariomod = new javax.swing.JDialog();
        titJdiag1 = new javax.swing.JLabel();
        titnomInvdiag1 = new javax.swing.JLabel();
        txtfieldNomInv1 = new javax.swing.JTextField();
        titcantInvdiag1 = new javax.swing.JLabel();
        txtfieldcantInvdiag1 = new javax.swing.JTextField();
        titprecInvdiag1 = new javax.swing.JLabel();
        txtfieldprecInvdiag1 = new javax.swing.JTextField();
        diagagreInv1 = new javax.swing.JButton();
        scrollClientes = new javax.swing.JScrollPane();
        tablaInventario = new javax.swing.JTable();
        Titulo = new javax.swing.JLabel();
        agregar = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        eliminar1 = new javax.swing.JButton();

        datosInventario.setBounds(new java.awt.Rectangle(100, 100, 260, 280));

        titJdiag.setText("Ingrese los datos del producto");

        titnomInvdiag.setText("Nombre del producto");

        titCantInvdiag.setText("Cantidad");

        titprecInvdiag.setText("Precio unitario");

        diagagreInv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Add.png"))); // NOI18N
        diagagreInv.setText("Agregar");
        diagagreInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagagreInvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout datosInventarioLayout = new javax.swing.GroupLayout(datosInventario.getContentPane());
        datosInventario.getContentPane().setLayout(datosInventarioLayout);
        datosInventarioLayout.setHorizontalGroup(
            datosInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datosInventarioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(diagagreInv)
                .addGap(61, 61, 61))
            .addGroup(datosInventarioLayout.createSequentialGroup()
                .addGroup(datosInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datosInventarioLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(titJdiag))
                    .addGroup(datosInventarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(datosInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titnomInvdiag)
                            .addComponent(titCantInvdiag)
                            .addComponent(titprecInvdiag))
                        .addGap(4, 4, 4)
                        .addGroup(datosInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtfieldNomInv, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(txtfieldcantInvdiag)
                            .addComponent(txtfieldprecInvdiag))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        datosInventarioLayout.setVerticalGroup(
            datosInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosInventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titJdiag)
                .addGap(32, 32, 32)
                .addGroup(datosInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfieldNomInv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titnomInvdiag))
                .addGap(18, 18, 18)
                .addGroup(datosInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfieldcantInvdiag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titCantInvdiag))
                .addGap(18, 18, 18)
                .addGroup(datosInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfieldprecInvdiag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titprecInvdiag))
                .addGap(35, 35, 35)
                .addComponent(diagagreInv)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        datosInventariomod.setBounds(new java.awt.Rectangle(100, 200, 260, 280));

        titJdiag1.setText("Ingrese los datos del producto");

        titnomInvdiag1.setText("Nombre del producto");

        titcantInvdiag1.setText("Cantidad");

        titprecInvdiag1.setText("Precio unitario");

        diagagreInv1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Add.png"))); // NOI18N
        diagagreInv1.setText("Agregar");
        diagagreInv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagagreInv1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout datosInventariomodLayout = new javax.swing.GroupLayout(datosInventariomod.getContentPane());
        datosInventariomod.getContentPane().setLayout(datosInventariomodLayout);
        datosInventariomodLayout.setHorizontalGroup(
            datosInventariomodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosInventariomodLayout.createSequentialGroup()
                .addGroup(datosInventariomodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datosInventariomodLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(titJdiag1))
                    .addGroup(datosInventariomodLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(datosInventariomodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titnomInvdiag1)
                            .addComponent(titcantInvdiag1)
                            .addComponent(titprecInvdiag1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(datosInventariomodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtfieldcantInvdiag1, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(txtfieldNomInv1)
                            .addComponent(txtfieldprecInvdiag1))))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datosInventariomodLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(diagagreInv1)
                .addGap(66, 66, 66))
        );
        datosInventariomodLayout.setVerticalGroup(
            datosInventariomodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosInventariomodLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titJdiag1)
                .addGap(29, 29, 29)
                .addGroup(datosInventariomodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfieldNomInv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titnomInvdiag1))
                .addGap(18, 18, 18)
                .addGroup(datosInventariomodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfieldcantInvdiag1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titcantInvdiag1))
                .addGap(18, 18, 18)
                .addGroup(datosInventariomodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfieldprecInvdiag1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titprecInvdiag1))
                .addGap(38, 38, 38)
                .addComponent(diagagreInv1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Facturación Tienda Nordic Style");
        setBackground(new java.awt.Color(102, 102, 102));

        tablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Precio", "Cantidad"
            }
        ));
        tablaInventario.getTableHeader().setReorderingAllowed(false);
        scrollClientes.setViewportView(tablaInventario);
        tablaInventario.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        Titulo.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Menú de Mantenimiento de inventario");

        agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Add.png"))); // NOI18N
        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Edit.png"))); // NOI18N
        editar.setText("Editar");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Remove.png"))); // NOI18N
        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        eliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Salir2.png"))); // NOI18N
        eliminar1.setText("Salir");
        eliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(agregar)
                            .addComponent(editar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(scrollClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(Titulo)))
                .addGap(0, 48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(agregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eliminar1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(scrollClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        if (evt.getSource()== agregar) {
            datosInventario.setVisible(true);
        }
    }//GEN-LAST:event_agregarActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        if (evt.getSource()== editar)
            datosInventariomod.setVisible(true);
    }//GEN-LAST:event_editarActionPerformed
    public void inventarioBase(){
        Main.inv.add(new Articulos(1001, "Jeans Mezclilla", "34", "22450"));
        Main.inv.add(new Articulos(1002,"Camisa manga larga","45","14700"));
        Main.inv.add(new Articulos(1003,"Pijama 2 piezas","20","16115"));
        Main.inv.add(new Articulos(1004,"Blusa","50","8990"));
        Main.inv.add(new Articulos(1005,"Chaleco","25","12700"));
        Main.inv.add(new Articulos(1006,"Jacket mezclilla","18","25300"));
        Main.inv.add(new Articulos(1007,"Cardigan","36","21900"));
        Main.inv.add(new Articulos(1008,"Sueter","45","13670"));
        Main.inv.add(new Articulos(1009,"Botines","28","22990"));
        Main.inv.add(new Articulos(1010,"Tennis","45","24560"));
        cargarInventario();
    }
    private void diagagreInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagagreInvActionPerformed
        // TODO add your handling code here:
        Articulos articulo1 = new Articulos();
        String cantidad = null;
        articulo1.setInvNombre(txtfieldNomInv.getText());
        articulo1.setCantDisp(txtfieldcantInvdiag.getText());
        articulo1.setPrecio(txtfieldprecInvdiag.getText());
        articulo1.setPosicion(00+Main.inv.size());
        
        Main.inv.add(articulo1);
        JOptionPane.showMessageDialog(this, "Articulo ingresado exitosamente con el numero: 00"+ articulo1.getPosicion());
        txtfieldNomInv.setText("");
        txtfieldcantInvdiag.setText("");
        txtfieldprecInvdiag.setText("");
        cargarInventario();
    }//GEN-LAST:event_diagagreInvActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        int eliminarFila=tablaInventario.getSelectedRow();
        if (eliminarFila>=0) {
            Main.inv.remove(eliminarFila);
            cargarInventario();
        } 
    }//GEN-LAST:event_eliminarActionPerformed

    private void diagagreInv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagagreInv1ActionPerformed
       Articulos articulomod = new Articulos();
        int modificarFila=tablaInventario.getSelectedRow();
        if (modificarFila>=0) {
            articulomod.setInvNombre(txtfieldNomInv1.getText());
            articulomod.setCantDisp(txtfieldcantInvdiag1.getText());
            articulomod.setPrecio(txtfieldprecInvdiag1.getText());
            articulomod.setPosicion(00+Main.inv.size());
            Main.inv.set(modificarFila, articulomod);
            cargarInventario();
        } 
        JOptionPane.showMessageDialog(this, "Cliente modificado exitosamente con el numero: 00"+ articulomod.getPosicion());
        txtfieldNomInv1.setText("");
        txtfieldcantInvdiag1.setText("");
        txtfieldprecInvdiag1.setText("");
        cargarInventario();
    }//GEN-LAST:event_diagagreInv1ActionPerformed

    private void eliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_eliminar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void cargarInventario(){
        DefaultTableModel modelo = new DefaultTableModel(new String[]{"Codigo", "Nombre", "Cantidad", "Precio unitario"}, Main.inv.size());
        tablaInventario.setModel(modelo);
        
        TableModel modeloDatos= tablaInventario.getModel();
        for (int i = 0; i < Main.inv.size(); i++) {
            Articulos articulo1=Main.inv.get(i);
            modeloDatos.setValueAt(articulo1.getPosicion(), i, 0);
            modeloDatos.setValueAt(articulo1.getInvNombre(), i, 1);
            modeloDatos.setValueAt(articulo1.getCantDisp(), i, 2);
            modeloDatos.setValueAt(articulo1.getPrecio(), i, 3);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton agregar;
    private javax.swing.JDialog datosInventario;
    private javax.swing.JDialog datosInventariomod;
    private javax.swing.JButton diagagreInv;
    private javax.swing.JButton diagagreInv1;
    private javax.swing.JButton editar;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton eliminar1;
    private javax.swing.JScrollPane scrollClientes;
    private javax.swing.JTable tablaInventario;
    private javax.swing.JLabel titCantInvdiag;
    private javax.swing.JLabel titJdiag;
    private javax.swing.JLabel titJdiag1;
    private javax.swing.JLabel titcantInvdiag1;
    private javax.swing.JLabel titnomInvdiag;
    private javax.swing.JLabel titnomInvdiag1;
    private javax.swing.JLabel titprecInvdiag;
    private javax.swing.JLabel titprecInvdiag1;
    private javax.swing.JTextField txtfieldNomInv;
    private javax.swing.JTextField txtfieldNomInv1;
    private javax.swing.JTextField txtfieldcantInvdiag;
    private javax.swing.JTextField txtfieldcantInvdiag1;
    private javax.swing.JTextField txtfieldprecInvdiag;
    private javax.swing.JTextField txtfieldprecInvdiag1;
    // End of variables declaration//GEN-END:variables

    
}
